cartpole1:
  env_id: CartPole-v1
  replay_buffer_size: 100000
  batch_size: 32
  gamma: 0.99
  learning_rate: 0.001
  epsilon_start: 1.0
  epsilon_end: 0.1
  epsilon_decay: 0.995
  epsilon_min: 0.05
  target_update: 10
